# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 530)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_add_coffee = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add_coffee.setObjectName("btn_add_coffee")
        self.gridLayout.addWidget(self.btn_add_coffee, 0, 0, 1, 1)
        self.btn_edit_coffe = QtWidgets.QPushButton(self.centralwidget)
        self.btn_edit_coffe.setObjectName("btn_edit_coffe")
        self.gridLayout.addWidget(self.btn_edit_coffe, 0, 1, 1, 1)
        self.coffee_table = QtWidgets.QTableWidget(self.centralwidget)
        self.coffee_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.coffee_table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.coffee_table.setTabKeyNavigation(True)
        self.coffee_table.setProperty("showDropIndicator", True)
        self.coffee_table.setDragEnabled(False)
        self.coffee_table.setDragDropOverwriteMode(True)
        self.coffee_table.setDragDropMode(QtWidgets.QAbstractItemView.NoDragDrop)
        self.coffee_table.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.coffee_table.setAlternatingRowColors(False)
        self.coffee_table.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.coffee_table.setTextElideMode(QtCore.Qt.ElideRight)
        self.coffee_table.setObjectName("coffee_table")
        self.coffee_table.setColumnCount(0)
        self.coffee_table.setRowCount(0)
        self.coffee_table.horizontalHeader().setVisible(True)
        self.coffee_table.horizontalHeader().setCascadingSectionResizes(False)
        self.coffee_table.horizontalHeader().setHighlightSections(True)
        self.coffee_table.horizontalHeader().setSortIndicatorShown(False)
        self.coffee_table.horizontalHeader().setStretchLastSection(False)
        self.coffee_table.verticalHeader().setCascadingSectionResizes(False)
        self.coffee_table.verticalHeader().setHighlightSections(True)
        self.coffee_table.verticalHeader().setStretchLastSection(False)
        self.gridLayout.addWidget(self.coffee_table, 1, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Капучино"))
        self.btn_add_coffee.setText(_translate("MainWindow", "Добавить кофе"))
        self.btn_edit_coffe.setText(_translate("MainWindow", "Изменить кофе"))
